name: Update GitHub Stats

on:
  schedule:
    # Runs every 24 hours
    - cron: '0 0 * * *'
  # Allows you to run this manually from the Actions tab for testing
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate GitHub Stats
        uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.USER_TOKEN }} # We will create this in Step 2
          
      - name: Update README
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Update README stats"
            git push
          fi
